apiVersion: v1
kind: Service
metadata:
  name: live-on-fe
  labels:
    app: live-on-fe
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: live-on-fe
  type: LoadBalancer
