apiVersion: v1
kind: Service
metadata:
  name: live-on-fe
  labels:
    app: live-on-fe
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: live-on-fe
  type: LoadBalancer
