name: CI/CD to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 615299753054.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t 615299753054.dkr.ecr.us-east-1.amazonaws.com/fronttest/wookjin:latest .

    - name: Push Docker Image to ECR
      run: |
        docker tag 615299753054.dkr.ecr.us-east-1.amazonaws.com/fronttest/wookjin:latest 615299753054.dkr.ecr.us-east-1.amazonaws.com/fronttest/wookjin:latest
        docker push 615299753054.dkr.ecr.us-east-1.amazonaws.com/fronttest/wookjin:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f wookjin.yaml
        kubectl rollout status deployment/wookjin-front-test
